/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Symon Hasan
 */
public class AdminPanel extends javax.swing.JFrame {

    Connection conn=null;
    private Object Connect;
    
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminTopPanel = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AdminMenuPanel = new javax.swing.JPanel();
        newaccount = new javax.swing.JLabel();
        deposite = new javax.swing.JLabel();
        withdraw = new javax.swing.JLabel();
        searchac = new javax.swing.JLabel();
        adminchangeinfo = new javax.swing.JLabel();
        processclose = new javax.swing.JLabel();
        HoverPanel = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        searchicon = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        signout = new javax.swing.JLabel();
        DepositePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        damount = new javax.swing.JTextField();
        dacno = new javax.swing.JTextField();
        depositebutton = new javax.swing.JButton();
        WithdrawPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        wacno = new javax.swing.JTextField();
        wamount = new javax.swing.JTextField();
        withdrawbutton = new javax.swing.JButton();
        SearchAccountPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        searchacno = new javax.swing.JTextField();
        searchshow = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ssactivation = new javax.swing.JLabel();
        ssname = new javax.swing.JLabel();
        ssacno = new javax.swing.JLabel();
        ssbranch = new javax.swing.JLabel();
        ssbalance = new javax.swing.JLabel();
        ssnidno = new javax.swing.JLabel();
        ssinterest = new javax.swing.JLabel();
        ssemail = new javax.swing.JLabel();
        ssaddress = new javax.swing.JLabel();
        sscardno = new javax.swing.JLabel();
        ssissuedate = new javax.swing.JLabel();
        ssexpiredate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        ClosingRequestPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        showlist = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ChangeInfoPanel = new javax.swing.JPanel();
        cititle = new javax.swing.JLabel();
        hint = new javax.swing.JLabel();
        cinew = new javax.swing.JTextField();
        ciaccountno = new javax.swing.JTextField();
        cichange = new javax.swing.JButton();
        selectionpanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        ciinterestrate = new javax.swing.JLabel();
        ciacno = new javax.swing.JLabel();
        cicardno = new javax.swing.JLabel();
        cibranch = new javax.swing.JLabel();
        ciexpiredate = new javax.swing.JLabel();
        cinidno = new javax.swing.JLabel();
        change = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        AdminTopPanel.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Close.png"))); // NOI18N
        close.setText("jLabel1");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        AdminTopPanel.add(close);
        close.setBounds(870, 0, 30, 25);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        AdminTopPanel.add(minimize);
        minimize.setBounds(840, 0, 25, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/hover_mainui.jpg"))); // NOI18N
        AdminTopPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 25);

        getContentPane().add(AdminTopPanel);
        AdminTopPanel.setBounds(0, 0, 900, 25);

        AdminMenuPanel.setBackground(new java.awt.Color(189, 195, 199));
        AdminMenuPanel.setMaximumSize(new java.awt.Dimension(900, 450));
        AdminMenuPanel.setMinimumSize(new java.awt.Dimension(900, 450));
        AdminMenuPanel.setPreferredSize(new java.awt.Dimension(900, 450));
        AdminMenuPanel.setLayout(null);

        newaccount.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        newaccount.setForeground(java.awt.SystemColor.textHighlight);
        newaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/newaccount.png"))); // NOI18N
        newaccount.setText("New Account");
        newaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newaccountMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(newaccount);
        newaccount.setBounds(130, 200, 270, 50);

        deposite.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        deposite.setForeground(java.awt.SystemColor.textHighlight);
        deposite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Deposite.png"))); // NOI18N
        deposite.setText("Deposite");
        deposite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deposite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositeMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(deposite);
        deposite.setBounds(130, 100, 270, 50);

        withdraw.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        withdraw.setForeground(java.awt.SystemColor.textHighlight);
        withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/withdraw.png"))); // NOI18N
        withdraw.setText("Withdraw");
        withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(withdraw);
        withdraw.setBounds(500, 100, 280, 50);

        searchac.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        searchac.setForeground(java.awt.SystemColor.textHighlight);
        searchac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/SearchAc.png"))); // NOI18N
        searchac.setText("Search Account");
        searchac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchacMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(searchac);
        searchac.setBounds(500, 200, 300, 50);

        adminchangeinfo.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        adminchangeinfo.setForeground(java.awt.SystemColor.textHighlight);
        adminchangeinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/ChangeInfo.png"))); // NOI18N
        adminchangeinfo.setText("Change  Information");
        adminchangeinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminchangeinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminchangeinfoMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(adminchangeinfo);
        adminchangeinfo.setBounds(130, 300, 270, 50);

        processclose.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        processclose.setForeground(java.awt.SystemColor.textHighlight);
        processclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Closing Request.png"))); // NOI18N
        processclose.setText("Process Closing  Request");
        processclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        processclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processcloseMouseClicked(evt);
            }
        });
        AdminMenuPanel.add(processclose);
        processclose.setBounds(490, 300, 330, 50);

        getContentPane().add(AdminMenuPanel);
        AdminMenuPanel.setBounds(0, 180, 900, 420);

        HoverPanel.setBackground(new java.awt.Color(29, 29, 29));
        HoverPanel.setLayout(null);

        back.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Back.png"))); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        HoverPanel.add(back);
        back.setBounds(0, 0, 100, 50);

        searchbox.setBackground(new java.awt.Color(29, 29, 29));
        searchbox.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        searchbox.setForeground(new java.awt.Color(255, 255, 255));
        searchbox.setText("Search");
        searchbox.setBorder(null);
        HoverPanel.add(searchbox);
        searchbox.setBounds(530, 30, 290, 30);

        searchicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/searchicon.png"))); // NOI18N
        HoverPanel.add(searchicon);
        searchicon.setBounds(830, 30, 30, 30);

        menu.setFont(new java.awt.Font("Prestige Elite Std", 0, 16)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/menuicon.png"))); // NOI18N
        menu.setText("Menu");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        HoverPanel.add(menu);
        menu.setBounds(20, 110, 120, 40);

        notification.setFont(new java.awt.Font("Prestige Elite Std", 0, 16)); // NOI18N
        notification.setForeground(new java.awt.Color(255, 255, 255));
        notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/notification.png"))); // NOI18N
        notification.setText("Notifiction");
        notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationMouseClicked(evt);
            }
        });
        HoverPanel.add(notification);
        notification.setBounds(160, 110, 140, 40);

        signout.setFont(new java.awt.Font("Prestige Elite Std", 0, 16)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/logout.png"))); // NOI18N
        signout.setText("Signout");
        signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutMouseClicked(evt);
            }
        });
        HoverPanel.add(signout);
        signout.setBounds(330, 110, 110, 40);

        getContentPane().add(HoverPanel);
        HoverPanel.setBounds(0, 20, 900, 160);

        DepositePanel.setBackground(new java.awt.Color(189, 195, 199));
        DepositePanel.setMaximumSize(new java.awt.Dimension(900, 420));
        DepositePanel.setMinimumSize(new java.awt.Dimension(900, 420));
        DepositePanel.setPreferredSize(new java.awt.Dimension(900, 420));
        DepositePanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Deposite.png"))); // NOI18N
        jLabel2.setText("Deposite");
        DepositePanel.add(jLabel2);
        jLabel2.setBounds(240, 40, 360, 50);

        damount.setBackground(new java.awt.Color(189, 195, 199));
        damount.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        damount.setText("Amount");
        damount.setBorder(null);
        damount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                damountMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                damountMouseExited(evt);
            }
        });
        DepositePanel.add(damount);
        damount.setBounds(260, 220, 420, 40);

        dacno.setBackground(new java.awt.Color(189, 195, 199));
        dacno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        dacno.setText("Account No");
        dacno.setBorder(null);
        dacno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dacnoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dacnoMouseExited(evt);
            }
        });
        DepositePanel.add(dacno);
        dacno.setBounds(260, 150, 420, 40);

        depositebutton.setBackground(new java.awt.Color(189, 195, 199));
        depositebutton.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        depositebutton.setText("Deposite");
        depositebutton.setBorder(null);
        depositebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositebuttonMouseClicked(evt);
            }
        });
        DepositePanel.add(depositebutton);
        depositebutton.setBounds(330, 320, 220, 40);

        getContentPane().add(DepositePanel);
        DepositePanel.setBounds(0, 180, 900, 420);

        WithdrawPanel.setBackground(new java.awt.Color(189, 195, 199));
        WithdrawPanel.setMaximumSize(new java.awt.Dimension(900, 420));
        WithdrawPanel.setMinimumSize(new java.awt.Dimension(900, 420));
        WithdrawPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/withdraw.png"))); // NOI18N
        jLabel3.setText("Withdraw");
        WithdrawPanel.add(jLabel3);
        jLabel3.setBounds(240, 40, 360, 50);

        wacno.setBackground(new java.awt.Color(189, 195, 199));
        wacno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        wacno.setText("Account No");
        wacno.setBorder(null);
        wacno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wacnoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wacnoMouseExited(evt);
            }
        });
        WithdrawPanel.add(wacno);
        wacno.setBounds(260, 150, 420, 40);

        wamount.setBackground(new java.awt.Color(189, 195, 199));
        wamount.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        wamount.setText("Amount");
        wamount.setBorder(null);
        wamount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wamountMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wamountMouseExited(evt);
            }
        });
        WithdrawPanel.add(wamount);
        wamount.setBounds(260, 220, 420, 40);

        withdrawbutton.setBackground(new java.awt.Color(189, 195, 199));
        withdrawbutton.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        withdrawbutton.setText("Withdraw");
        withdrawbutton.setBorder(null);
        withdrawbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawbuttonMouseClicked(evt);
            }
        });
        WithdrawPanel.add(withdrawbutton);
        withdrawbutton.setBounds(330, 320, 220, 40);

        getContentPane().add(WithdrawPanel);
        WithdrawPanel.setBounds(0, 180, 900, 420);

        SearchAccountPanel.setBackground(new java.awt.Color(189, 195, 199));
        SearchAccountPanel.setMaximumSize(new java.awt.Dimension(900, 420));
        SearchAccountPanel.setMinimumSize(new java.awt.Dimension(900, 420));
        SearchAccountPanel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/SearchAc.png"))); // NOI18N
        jLabel6.setText("Search Account");
        SearchAccountPanel.add(jLabel6);
        jLabel6.setBounds(240, 10, 360, 50);

        searchacno.setBackground(new java.awt.Color(189, 195, 199));
        searchacno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        searchacno.setText("Account No");
        searchacno.setBorder(null);
        searchacno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchacnoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchacnoMouseExited(evt);
            }
        });
        SearchAccountPanel.add(searchacno);
        searchacno.setBounds(290, 150, 320, 40);

        searchshow.setBackground(new java.awt.Color(51, 153, 255));
        searchshow.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        jLabel4.setText("Details");
        searchshow.add(jLabel4);
        jLabel4.setBounds(20, 20, 170, 40);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        searchshow.add(jSeparator2);
        jSeparator2.setBounds(240, 50, 10, 330);

        ssactivation.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssactivation.setForeground(new java.awt.Color(255, 255, 255));
        ssactivation.setText("Activation Status");
        searchshow.add(ssactivation);
        ssactivation.setBounds(270, 330, 220, 30);

        ssname.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssname.setForeground(new java.awt.Color(255, 255, 255));
        ssname.setText("Name");
        searchshow.add(ssname);
        ssname.setBounds(10, 80, 220, 30);

        ssacno.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssacno.setForeground(new java.awt.Color(255, 255, 255));
        ssacno.setText("A/C No");
        searchshow.add(ssacno);
        ssacno.setBounds(10, 130, 220, 30);

        ssbranch.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssbranch.setForeground(new java.awt.Color(255, 255, 255));
        ssbranch.setText("Branch");
        searchshow.add(ssbranch);
        ssbranch.setBounds(10, 180, 220, 30);

        ssbalance.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssbalance.setForeground(new java.awt.Color(255, 255, 255));
        ssbalance.setText("Balance");
        searchshow.add(ssbalance);
        ssbalance.setBounds(10, 230, 220, 30);

        ssnidno.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssnidno.setForeground(new java.awt.Color(255, 255, 255));
        ssnidno.setText("NID No");
        searchshow.add(ssnidno);
        ssnidno.setBounds(10, 280, 220, 30);

        ssinterest.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssinterest.setForeground(new java.awt.Color(255, 255, 255));
        ssinterest.setText("Interest Rate");
        searchshow.add(ssinterest);
        ssinterest.setBounds(10, 330, 220, 30);

        ssemail.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssemail.setForeground(new java.awt.Color(255, 255, 255));
        ssemail.setText("Email");
        searchshow.add(ssemail);
        ssemail.setBounds(270, 80, 220, 30);

        ssaddress.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssaddress.setForeground(new java.awt.Color(255, 255, 255));
        ssaddress.setText("Address");
        searchshow.add(ssaddress);
        ssaddress.setBounds(270, 130, 220, 30);

        sscardno.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        sscardno.setForeground(new java.awt.Color(255, 255, 255));
        sscardno.setText("Card No");
        searchshow.add(sscardno);
        sscardno.setBounds(270, 180, 220, 30);

        ssissuedate.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssissuedate.setForeground(new java.awt.Color(255, 255, 255));
        ssissuedate.setText("Issue Date");
        searchshow.add(ssissuedate);
        ssissuedate.setBounds(270, 230, 220, 30);

        ssexpiredate.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        ssexpiredate.setForeground(new java.awt.Color(255, 255, 255));
        ssexpiredate.setText("Expire Date");
        searchshow.add(ssexpiredate);
        ssexpiredate.setBounds(270, 280, 220, 30);
        searchshow.add(jSeparator1);
        jSeparator1.setBounds(0, 380, 520, 20);
        searchshow.add(jSeparator3);
        jSeparator3.setBounds(0, 50, 520, 20);

        SearchAccountPanel.add(searchshow);
        searchshow.setBounds(0, 0, 520, 420);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Search.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        SearchAccountPanel.add(jLabel5);
        jLabel5.setBounds(620, 150, 50, 50);

        getContentPane().add(SearchAccountPanel);
        SearchAccountPanel.setBounds(0, 180, 900, 420);

        ClosingRequestPanel.setBackground(new java.awt.Color(189, 195, 199));
        ClosingRequestPanel.setMaximumSize(new java.awt.Dimension(900, 420));
        ClosingRequestPanel.setMinimumSize(new java.awt.Dimension(900, 420));
        ClosingRequestPanel.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Closing Request.png"))); // NOI18N
        jLabel7.setText("Closing Request Process");
        ClosingRequestPanel.add(jLabel7);
        jLabel7.setBounds(250, 30, 360, 50);

        showlist.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        showlist.setText("<html></html>");
        ClosingRequestPanel.add(showlist);
        showlist.setBounds(90, 120, 710, 160);

        jButton1.setBackground(new java.awt.Color(189, 195, 199));
        jButton1.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jButton1.setText("Process");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        ClosingRequestPanel.add(jButton1);
        jButton1.setBounds(350, 310, 190, 50);

        getContentPane().add(ClosingRequestPanel);
        ClosingRequestPanel.setBounds(0, 180, 900, 420);

        ChangeInfoPanel.setBackground(new java.awt.Color(189, 195, 199));
        ChangeInfoPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChangeInfoPanelMouseMoved(evt);
            }
        });
        ChangeInfoPanel.setLayout(null);

        cititle.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        cititle.setForeground(new java.awt.Color(255, 255, 255));
        cititle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cititle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/ChangeInfo.png"))); // NOI18N
        cititle.setText("Change Information");
        ChangeInfoPanel.add(cititle);
        cititle.setBounds(260, 40, 360, 50);

        hint.setForeground(new java.awt.Color(255, 255, 255));
        hint.setText("<html>Move Your Cursor Towards Left To Enable Selection Menu. Then Select Which Information You Want To Change.</html>");
        ChangeInfoPanel.add(hint);
        hint.setBounds(370, 70, 430, 50);

        cinew.setBackground(new java.awt.Color(189, 195, 199));
        cinew.setFont(new java.awt.Font("Prestige Elite Std", 0, 11)); // NOI18N
        cinew.setForeground(new java.awt.Color(255, 255, 255));
        cinew.setText("New");
        cinew.setBorder(null);
        cinew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinewMouseClicked(evt);
            }
        });
        ChangeInfoPanel.add(cinew);
        cinew.setBounds(380, 270, 430, 40);

        ciaccountno.setBackground(new java.awt.Color(189, 195, 199));
        ciaccountno.setFont(new java.awt.Font("Prestige Elite Std", 0, 11)); // NOI18N
        ciaccountno.setForeground(new java.awt.Color(255, 255, 255));
        ciaccountno.setText("Account No");
        ciaccountno.setBorder(null);
        ciaccountno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciaccountnoMouseClicked(evt);
            }
        });
        ChangeInfoPanel.add(ciaccountno);
        ciaccountno.setBounds(380, 190, 430, 40);

        cichange.setBackground(new java.awt.Color(189, 195, 199));
        cichange.setForeground(java.awt.SystemColor.textHighlight);
        cichange.setText("Change");
        cichange.setBorder(null);
        cichange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cichangeMouseClicked(evt);
            }
        });
        ChangeInfoPanel.add(cichange);
        cichange.setBounds(460, 350, 230, 40);

        selectionpanel.setBackground(new java.awt.Color(206, 228, 233));
        selectionpanel.setMaximumSize(new java.awt.Dimension(300, 420));
        selectionpanel.setMinimumSize(new java.awt.Dimension(300, 420));
        selectionpanel.setPreferredSize(new java.awt.Dimension(300, 420));
        selectionpanel.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Prestige Elite Std", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Selection Menu");
        selectionpanel.add(jLabel25);
        jLabel25.setBounds(20, 50, 220, 30);

        ciinterestrate.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        ciinterestrate.setForeground(java.awt.SystemColor.textHighlight);
        ciinterestrate.setText("Interest Rate");
        ciinterestrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciinterestrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciinterestrateMouseClicked(evt);
            }
        });
        selectionpanel.add(ciinterestrate);
        ciinterestrate.setBounds(20, 350, 160, 40);

        ciacno.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        ciacno.setForeground(java.awt.SystemColor.textHighlight);
        ciacno.setText("Account No");
        ciacno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciacno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciacnoMouseClicked(evt);
            }
        });
        selectionpanel.add(ciacno);
        ciacno.setBounds(20, 100, 160, 40);

        cicardno.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        cicardno.setForeground(java.awt.SystemColor.textHighlight);
        cicardno.setText("Card No");
        cicardno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cicardno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cicardnoMouseClicked(evt);
            }
        });
        selectionpanel.add(cicardno);
        cicardno.setBounds(20, 150, 160, 40);

        cibranch.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        cibranch.setForeground(java.awt.SystemColor.textHighlight);
        cibranch.setText("Branch");
        cibranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cibranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cibranchMouseClicked(evt);
            }
        });
        selectionpanel.add(cibranch);
        cibranch.setBounds(20, 200, 160, 40);

        ciexpiredate.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        ciexpiredate.setForeground(java.awt.SystemColor.textHighlight);
        ciexpiredate.setText("Expire Date");
        ciexpiredate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciexpiredate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciexpiredateMouseClicked(evt);
            }
        });
        selectionpanel.add(ciexpiredate);
        ciexpiredate.setBounds(20, 250, 160, 40);

        cinidno.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        cinidno.setForeground(java.awt.SystemColor.textHighlight);
        cinidno.setText("NID No");
        cinidno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinidno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinidnoMouseClicked(evt);
            }
        });
        selectionpanel.add(cinidno);
        cinidno.setBounds(20, 300, 160, 40);

        ChangeInfoPanel.add(selectionpanel);
        selectionpanel.setBounds(0, 0, 300, 420);

        change.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        change.setForeground(java.awt.SystemColor.textHighlight);
        change.setText("Change");
        ChangeInfoPanel.add(change);
        change.setBounds(380, 140, 140, 30);

        getContentPane().add(ChangeInfoPanel);
        ChangeInfoPanel.setBounds(0, 180, 900, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(UserLogin.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        
    
    }//GEN-LAST:event_backMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        AdminMenuPanel.setVisible(true);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(false);
        selectionpanel.setVisible(false);
        searchshow.setVisible(false);
        
    }//GEN-LAST:event_menuMouseClicked

    private void notificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationMouseClicked

    private void signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseClicked
        AdminLogin AL=new AdminLogin();
        AL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signoutMouseClicked

    private void cinewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinewMouseClicked
        cinew.setForeground(Color.white);
        cinew.setText("");

    }//GEN-LAST:event_cinewMouseClicked

    private void ciaccountnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciaccountnoMouseClicked
        ciaccountno.setForeground(Color.white);
        ciaccountno.setText("");
    }//GEN-LAST:event_ciaccountnoMouseClicked

    private void cichangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cichangeMouseClicked
        ResultSet rs=null;
        PreparedStatement ps=null;
        String s=new String();
        if(change.getText().equals("Account No"))
        {
                 try{

                    s="update Users set Account_No='"+cinew.getText()+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                   ciaccountno.setText("Unsucessfull!!"+e);
                }
            
        }
        if(change.getText().equals("Card No"))
        {
                try{

                    s="update Users set Card_No='"+cinew.getText()+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                   ciaccountno.setText("Unsucessfull!!");
                }
           
        }
        if(change.getText().equals("Branch"))
        {

                try{

                    s="update Users set Branch='"+cinew.getText()+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                   ciaccountno.setText("Unsucessfull!!");
                }
           
        }
        if(change.getText().equals("Expire Date"))
        {

            
                try{

                    s="update Users set Expire_Date='"+cinew.getText()+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                    ciaccountno.setText("Unsucessfull!!");
                }
           
        }
        if(change.getText().equals("NID No"))
        {

                try{

                    s="update Users set NID_No='"+cinew.getText()+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                    ciaccountno.setText("Unsucessfull!!");
                }
        }
        if(change.getText().equals("Interest Rate"))
        {

                try{
                    s="update Users set Interest_Rate='"+Double.parseDouble(cinew.getText())+"' where Account_No='"+ciaccountno.getText()+"'";
                    ps=conn.prepareStatement(s);
                    ps.executeUpdate();
                    
                }catch(Exception e){
                    ciaccountno.setText("Unsucessfull!!");
                }
            
        }
        try {
            rs.close();
            ps.close();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_cichangeMouseClicked

    private void ciinterestrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciinterestrateMouseClicked

        change.setText("Interest Rate");
    }//GEN-LAST:event_ciinterestrateMouseClicked

    private void ciacnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciacnoMouseClicked

        change.setText("Account No");

    }//GEN-LAST:event_ciacnoMouseClicked

    private void cicardnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cicardnoMouseClicked

        change.setText("Card No");
    }//GEN-LAST:event_cicardnoMouseClicked

    private void cibranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cibranchMouseClicked

        change.setText("Branch");
    }//GEN-LAST:event_cibranchMouseClicked

    private void ciexpiredateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciexpiredateMouseClicked

        change.setText("Expire Date");
    }//GEN-LAST:event_ciexpiredateMouseClicked

    private void cinidnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinidnoMouseClicked

        change.setText("NID No");
    }//GEN-LAST:event_cinidnoMouseClicked

    private void ChangeInfoPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeInfoPanelMouseMoved
        if(evt.getX()<280 && evt.getX()>=0)
        {
            selectionpanel.setVisible(true);
            hint.setVisible(false);
        }
        if(evt.getX()>=280)
        {
            selectionpanel.setVisible(false);
            hint.setVisible(true);
        }
    }//GEN-LAST:event_ChangeInfoPanelMouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        conn=Sqlite.ConnectDB();
        
        AdminMenuPanel.setVisible(true);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void depositeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositeMouseClicked
        AdminMenuPanel.setVisible(false);
        DepositePanel.setVisible(true);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(false);
    }//GEN-LAST:event_depositeMouseClicked

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        AdminMenuPanel.setVisible(false);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(true);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(false);
    }//GEN-LAST:event_withdrawMouseClicked

    private void searchacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchacMouseClicked
        AdminMenuPanel.setVisible(false);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(true);
        searchshow.setVisible(false);
        ChangeInfoPanel.setVisible(false);
    }//GEN-LAST:event_searchacMouseClicked

    private void adminchangeinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminchangeinfoMouseClicked
        AdminMenuPanel.setVisible(false);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(false);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(true);
        selectionpanel.setVisible(false);
    }//GEN-LAST:event_adminchangeinfoMouseClicked

    private void processcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processcloseMouseClicked
        AdminMenuPanel.setVisible(false);
        DepositePanel.setVisible(false);
        WithdrawPanel.setVisible(false);
        ClosingRequestPanel.setVisible(true);
        SearchAccountPanel.setVisible(false);
        ChangeInfoPanel.setVisible(false);
         ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
       String n="<html>You Have Closing Request From ";
      s="select * from Admin_Notification";
      try{
          ps=conn.prepareStatement(s);
          rs=ps.executeQuery();
          while(rs.next()){
          if(rs.getString("Request_Type").equals("Close")){
             n=n+"A/C No "+rs.getString("Account_No")+" ";
          }
          
         }

      }catch(Exception e){
          
      }
      showlist.setText(n+"</html>");
      
    }//GEN-LAST:event_processcloseMouseClicked

    private void newaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccountMouseClicked
        NewAccount NA=new NewAccount();
        NA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newaccountMouseClicked

    private void dacnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dacnoMouseClicked
       dacno.setText("");
    }//GEN-LAST:event_dacnoMouseClicked

    private void dacnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dacnoMouseExited
       if(dacno.getText().isEmpty())
       {
           dacno.setText("Account No");
       }
    }//GEN-LAST:event_dacnoMouseExited

    private void damountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damountMouseClicked
        damount.setText("");
    }//GEN-LAST:event_damountMouseClicked

    private void damountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damountMouseExited
        if(damount.getText().isEmpty())
       {
           damount.setText("Amount");
       }
    }//GEN-LAST:event_damountMouseExited

    private void depositebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositebuttonMouseClicked
        ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      boolean found=false;
      s="select * from Users";
      try{
          ps=conn.prepareStatement(s);
          rs=ps.executeQuery();
          while(rs.next()){
          if(dacno.getText().equals(rs.getString("Account_No"))){
              found=true;
              break;
          }
         }

      }catch(Exception e){
          
      }
      
      if(found)
      {
          try{
          s="update Users set Balance='"+(Double.parseDouble(rs.getString("Balance"))+Double.parseDouble(damount.getText()))+"' where Account_No='"+dacno.getText()+"'";
          ps=conn.prepareStatement(s);
          ps.executeUpdate();
          rs.close();
          ps.close(); 
          try{
          s="Insert into User_Notification values('"+dacno.getText()+"','"+"Deposite"+"','"+(damount.getText()+"Has Been Deposited To Your Account")+"','"+"No"+"')";
          ps=conn.prepareStatement(s);
          ps.execute();
          ps.close();
          dacno.setText("Deposited Sucessfully");
      }catch(Exception e){
          
      }
      }catch(Exception e){
          
      }
      
      }
      else
      {
          dacno.setText("Invalid Account No");
      }
    }//GEN-LAST:event_depositebuttonMouseClicked

    private void wacnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wacnoMouseClicked
        wacno.setText("");
    }//GEN-LAST:event_wacnoMouseClicked

    private void wamountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wamountMouseClicked
        wamount.setText("");
    }//GEN-LAST:event_wamountMouseClicked

    private void wacnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wacnoMouseExited
        if(wacno.getText().isEmpty())
        {
            wacno.setText("Account No");
        }
    }//GEN-LAST:event_wacnoMouseExited

    private void wamountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wamountMouseExited
        if(wamount.getText().isEmpty())
        {
            wamount.setText("Account No");
        }
    }//GEN-LAST:event_wamountMouseExited

    private void withdrawbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawbuttonMouseClicked
      ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      boolean found=false;
      String b;
      s="select * from Users";
      try{
          ps=conn.prepareStatement(s);
          rs=ps.executeQuery();
          while(rs.next()){
          if(wacno.getText().equals(rs.getString("Account_No"))){
              if(Double.parseDouble(wamount.getText())<= Double.parseDouble(rs.getString("Balance"))){
              found=true;
              
              break;
              }
          }
         }

      }catch(Exception e){
          
      }
      
      if(found)
      {
          
          try{
          s="update Users set Balance='"+(Double.parseDouble(rs.getString("Balance"))-Double.parseDouble(wamount.getText()))+"' where Account_No='"+wacno.getText()+"'";
          ps=conn.prepareStatement(s);
          ps.executeUpdate();
          rs.close();
          ps.close(); 
          try{
          s="Insert into User_Notification values('"+wacno.getText()+"','"+"Withdraw"+"','"+(wamount.getText()+" Has Been Withdrawn From Your Account")+"','"+"No"+"')";
          ps=conn.prepareStatement(s);
          ps.execute();
          ps.close();
          wacno.setText("Withdrawn Sucessfully");
      }catch(Exception e){
          
      }
      }catch(Exception e){
          
      }

      }
      else
      {
          wacno.setText("Invalid Account No");
      }
    }//GEN-LAST:event_withdrawbuttonMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      boolean found=false;
      s="select * from Users";
      try{
          ps=conn.prepareStatement(s);
          rs=ps.executeQuery();
          while(rs.next()){
          if(searchacno.getText().equals(rs.getString("Account_No"))){
              
              found=true;
              searchshow.setVisible(true);
              ssname.setText("Name | "+rs.getString("Name"));
              ssacno.setText("A/C No | "+rs.getString("Account_No"));
              ssbranch.setText("Branch | "+rs.getString("Branch_Name"));
              ssbalance.setText("Balance | "+rs.getString("Balance"));
              ssnidno.setText("NID No | "+rs.getString("NID_No"));
              ssinterest.setText("Interest_Rate | "+rs.getString("Interest_Rate"));
              ssemail.setText("Email | "+rs.getString("Email"));
              ssaddress.setText("Address|"+rs.getString("Address"));
              sscardno.setText("Card No | "+rs.getString("Card_No"));
              ssissuedate.setText("Issue Date | "+rs.getString("Issue_Date"));
              ssexpiredate.setText("Expire Date | "+rs.getString("Expire_Date"));
              ssactivation.setText("Activation Status | "+rs.getString("Activation_Status"));
              rs.close();
              ps.close();
              
              break;
             
          }
         }

      }catch(Exception e){
          
      }
      if(found)
      {
          
          jLabel6.setLocation(530, 10);
       searchacno.setLocation(530, 150);
       jLabel5.setLocation(850, 150);
      }
      else
      {
          searchacno.setText("Invalid Account No");
      }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void searchacnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchacnoMouseClicked
       
       searchshow.setVisible(false);
       jLabel6.setLocation(240, 10);
       searchacno.setLocation(290, 150);
       jLabel5.setLocation(620, 150);
       searchacno.setText("");
       
    }//GEN-LAST:event_searchacnoMouseClicked

    private void searchacnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchacnoMouseExited
        if(searchacno.getText().isEmpty())
        {
            searchacno.setText("Account No");
        }
    }//GEN-LAST:event_searchacnoMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
        try{
          s="Delete from Users where Closing_Request='"+"Yes"+"'";
          ps=conn.prepareStatement(s);
          ps.execute();
          try{
          s="update Admin_Notification set Read='"+"Yes"+"' where Request_Type='"+"Close"+"'";
          ps=conn.prepareStatement(s);
          ps.executeUpdate();
          s="Delete from Admin_Notification where Read='"+"Yes"+"'";
           ps=conn.prepareStatement(s);
          ps.executeUpdate();
          
      }catch(Exception e){
          System.out.println("Not");
      }
          JOptionPane.showMessageDialog(this,"Deleted Sucessfully");
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(this,"Invalid Account No");
      }
        try{
            rs.close();
          ps.close();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminMenuPanel;
    private javax.swing.JPanel AdminTopPanel;
    private javax.swing.JPanel ChangeInfoPanel;
    private javax.swing.JPanel ClosingRequestPanel;
    private javax.swing.JPanel DepositePanel;
    private javax.swing.JPanel HoverPanel;
    private javax.swing.JPanel SearchAccountPanel;
    private javax.swing.JPanel WithdrawPanel;
    private javax.swing.JLabel adminchangeinfo;
    private javax.swing.JLabel back;
    private javax.swing.JLabel change;
    private javax.swing.JTextField ciaccountno;
    private javax.swing.JLabel ciacno;
    private javax.swing.JLabel cibranch;
    private javax.swing.JLabel cicardno;
    private javax.swing.JButton cichange;
    private javax.swing.JLabel ciexpiredate;
    private javax.swing.JLabel ciinterestrate;
    private javax.swing.JTextField cinew;
    private javax.swing.JLabel cinidno;
    private javax.swing.JLabel cititle;
    private javax.swing.JLabel close;
    private javax.swing.JTextField dacno;
    private javax.swing.JTextField damount;
    private javax.swing.JLabel deposite;
    private javax.swing.JButton depositebutton;
    private javax.swing.JLabel hint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel newaccount;
    private javax.swing.JLabel notification;
    private javax.swing.JLabel processclose;
    private javax.swing.JLabel searchac;
    private javax.swing.JTextField searchacno;
    private javax.swing.JTextField searchbox;
    private javax.swing.JLabel searchicon;
    private javax.swing.JPanel searchshow;
    private javax.swing.JPanel selectionpanel;
    private javax.swing.JLabel showlist;
    private javax.swing.JLabel signout;
    private javax.swing.JLabel ssacno;
    private javax.swing.JLabel ssactivation;
    private javax.swing.JLabel ssaddress;
    private javax.swing.JLabel ssbalance;
    private javax.swing.JLabel ssbranch;
    private javax.swing.JLabel sscardno;
    private javax.swing.JLabel ssemail;
    private javax.swing.JLabel ssexpiredate;
    private javax.swing.JLabel ssinterest;
    private javax.swing.JLabel ssissuedate;
    private javax.swing.JLabel ssname;
    private javax.swing.JLabel ssnidno;
    private javax.swing.JTextField wacno;
    private javax.swing.JTextField wamount;
    private javax.swing.JLabel withdraw;
    private javax.swing.JButton withdrawbutton;
    // End of variables declaration//GEN-END:variables
}
