/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.sql.Connection;
import javax.swing.ImageIcon;

/**
 *
 * @author Symon Hasan
 */
public class MainUI extends javax.swing.JFrame {

   Connection conn=null;
    private Object Connect;
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usericon = new javax.swing.JLabel();
        adminicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 25));
        jPanel1.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Close.png"))); // NOI18N
        close.setText("jLabel1");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(870, 0, 30, 25);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(840, 0, 25, 25);

        hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/hover_mainui.jpg"))); // NOI18N
        jPanel1.add(hover);
        hover.setBounds(0, 0, 920, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 25);

        jPanel2.setMaximumSize(new java.awt.Dimension(900, 580));
        jPanel2.setLayout(null);

        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/UserB.png"))); // NOI18N
        usericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usericonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usericonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usericonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usericonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usericonMouseReleased(evt);
            }
        });
        jPanel2.add(usericon);
        usericon.setBounds(540, 180, 200, 210);

        adminicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/AdminB.png"))); // NOI18N
        adminicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminiconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminiconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminiconMouseReleased(evt);
            }
        });
        jPanel2.add(adminicon);
        adminicon.setBounds(150, 180, 200, 210);

        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ROLE");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 80, 180, 60);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MainUI.jpg"))); // NOI18N
        jPanel2.add(wallpaper);
        wallpaper.setBounds(0, 0, 900, 580);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 20, 900, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void usericonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/UserPressed.png"));
        usericon.setIcon(II);
    }//GEN-LAST:event_usericonMouseEntered

    private void usericonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/UserB.png"));
        usericon.setIcon(II);
    }//GEN-LAST:event_usericonMouseExited

    private void adminiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminiconMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/AdminPressed.png"));
        adminicon.setIcon(II);
    }//GEN-LAST:event_adminiconMouseEntered

    private void adminiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminiconMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/AdminB.png"));
        adminicon.setIcon(II);
    }//GEN-LAST:event_adminiconMouseExited

    private void adminiconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminiconMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/AdminClicked.png"));
        adminicon.setIcon(II);
    }//GEN-LAST:event_adminiconMousePressed

    private void usericonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMousePressed
       ImageIcon II=new ImageIcon(getClass().getResource("/Componants/UserClicked.png"));
        usericon.setIcon(II);
    }//GEN-LAST:event_usericonMousePressed

    private void adminiconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminiconMouseReleased
       ImageIcon II=new ImageIcon(getClass().getResource("/Componants/AdminPressed.png"));
        adminicon.setIcon(II);
    }//GEN-LAST:event_adminiconMouseReleased

    private void usericonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("/Componants/UserPressed.png"));
        usericon.setIcon(II);
    }//GEN-LAST:event_usericonMouseReleased

    private void adminiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminiconMouseClicked
        AdminLogin AL=new AdminLogin();
        AL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminiconMouseClicked

    private void usericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseClicked
       UserLogin UL=new UserLogin();
       UL.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_usericonMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(MainUI.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       conn=Sqlite.ConnectDB(); 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Thread.sleep(5000);
                }
                catch(Exception e)
                {
                    
                }
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminicon;
    private javax.swing.JLabel close;
    private javax.swing.JLabel hover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel usericon;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
