/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Symon Hasan
 */
public class NewAccount extends javax.swing.JFrame {

    Connection conn=null;
    private Object Connect;
    public NewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminTopPanel = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        issuedate = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        nidno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        cardno = new javax.swing.JTextField();
        expiredate = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        cardpin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        acno = new javax.swing.JTextField();
        actype = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        interestrate = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        AdminTopPanel.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Close.png"))); // NOI18N
        close.setText("jLabel1");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        AdminTopPanel.add(close);
        close.setBounds(870, 0, 30, 25);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        AdminTopPanel.add(minimize);
        minimize.setBounds(840, 0, 25, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/hover_mainui.jpg"))); // NOI18N
        AdminTopPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 25);

        getContentPane().add(AdminTopPanel);
        AdminTopPanel.setBounds(0, 0, 900, 25);

        MainPanel.setBackground(new java.awt.Color(44, 62, 80));
        MainPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/newaccount.png"))); // NOI18N
        jLabel2.setText("New Account");
        MainPanel.add(jLabel2);
        jLabel2.setBounds(240, 10, 360, 50);

        issuedate.setBackground(new java.awt.Color(116, 116, 116));
        issuedate.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        issuedate.setForeground(new java.awt.Color(255, 255, 255));
        issuedate.setText(" Issue Date");
        issuedate.setBorder(null);
        issuedate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuedateMouseClicked(evt);
            }
        });
        MainPanel.add(issuedate);
        issuedate.setBounds(470, 560, 380, 40);

        password.setBackground(new java.awt.Color(116, 116, 116));
        password.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText(" Password");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        MainPanel.add(password);
        password.setBounds(490, 460, 380, 40);

        gender.setBackground(new java.awt.Color(116, 116, 116));
        gender.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText(" Gender");
        gender.setBorder(null);
        gender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genderMouseClicked(evt);
            }
        });
        MainPanel.add(gender);
        gender.setBounds(50, 160, 380, 40);

        age.setBackground(new java.awt.Color(116, 116, 116));
        age.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText(" Age");
        age.setBorder(null);
        age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageMouseClicked(evt);
            }
        });
        MainPanel.add(age);
        age.setBounds(50, 220, 380, 40);

        nidno.setBackground(new java.awt.Color(116, 116, 116));
        nidno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        nidno.setForeground(new java.awt.Color(255, 255, 255));
        nidno.setText(" NID No");
        nidno.setBorder(null);
        nidno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nidnoMouseClicked(evt);
            }
        });
        MainPanel.add(nidno);
        nidno.setBounds(50, 280, 380, 40);

        email.setBackground(new java.awt.Color(116, 116, 116));
        email.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText(" Email");
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        MainPanel.add(email);
        email.setBounds(50, 340, 380, 40);

        contactno.setBackground(new java.awt.Color(116, 116, 116));
        contactno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        contactno.setForeground(new java.awt.Color(255, 255, 255));
        contactno.setText(" Contact No");
        contactno.setBorder(null);
        contactno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactnoMouseClicked(evt);
            }
        });
        MainPanel.add(contactno);
        contactno.setBounds(50, 460, 380, 40);

        cardno.setBackground(new java.awt.Color(116, 116, 116));
        cardno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        cardno.setForeground(new java.awt.Color(255, 255, 255));
        cardno.setText(" Card No");
        cardno.setBorder(null);
        cardno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardnoMouseClicked(evt);
            }
        });
        MainPanel.add(cardno);
        cardno.setBounds(50, 560, 380, 40);

        expiredate.setBackground(new java.awt.Color(116, 116, 116));
        expiredate.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        expiredate.setForeground(new java.awt.Color(255, 255, 255));
        expiredate.setText(" Expire Date");
        expiredate.setBorder(null);
        expiredate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiredateMouseClicked(evt);
            }
        });
        MainPanel.add(expiredate);
        expiredate.setBounds(470, 610, 380, 40);

        address.setBackground(new java.awt.Color(116, 116, 116));
        address.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText(" Address");
        address.setBorder(null);
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
        });
        MainPanel.add(address);
        address.setBounds(50, 400, 380, 40);

        cardpin.setBackground(new java.awt.Color(116, 116, 116));
        cardpin.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        cardpin.setForeground(new java.awt.Color(255, 255, 255));
        cardpin.setText(" Card Pin");
        cardpin.setBorder(null);
        cardpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardpinMouseClicked(evt);
            }
        });
        MainPanel.add(cardpin);
        cardpin.setBounds(50, 610, 380, 40);

        jSeparator1.setToolTipText("");
        MainPanel.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 880, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MainPanel.add(jSeparator2);
        jSeparator2.setBounds(890, 90, 10, 580);

        name.setBackground(new java.awt.Color(116, 116, 116));
        name.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText(" Name");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        MainPanel.add(name);
        name.setBounds(50, 100, 380, 40);

        acno.setBackground(new java.awt.Color(116, 116, 116));
        acno.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        acno.setForeground(new java.awt.Color(255, 255, 255));
        acno.setText(" A/C No");
        acno.setBorder(null);
        acno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acnoMouseClicked(evt);
            }
        });
        MainPanel.add(acno);
        acno.setBounds(490, 100, 380, 40);

        actype.setBackground(new java.awt.Color(116, 116, 116));
        actype.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        actype.setForeground(new java.awt.Color(255, 255, 255));
        actype.setText(" A/C Type");
        actype.setBorder(null);
        actype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actypeMouseClicked(evt);
            }
        });
        MainPanel.add(actype);
        actype.setBounds(490, 160, 380, 40);

        branch.setBackground(new java.awt.Color(116, 116, 116));
        branch.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        branch.setForeground(new java.awt.Color(255, 255, 255));
        branch.setText(" Branch");
        branch.setBorder(null);
        branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                branchMouseClicked(evt);
            }
        });
        MainPanel.add(branch);
        branch.setBounds(490, 220, 380, 40);

        interestrate.setBackground(new java.awt.Color(116, 116, 116));
        interestrate.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        interestrate.setForeground(new java.awt.Color(255, 255, 255));
        interestrate.setText(" Interest Rate");
        interestrate.setBorder(null);
        interestrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interestrateMouseClicked(evt);
            }
        });
        MainPanel.add(interestrate);
        interestrate.setBounds(490, 280, 380, 40);

        balance.setBackground(new java.awt.Color(116, 116, 116));
        balance.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText(" Balance");
        balance.setBorder(null);
        balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceMouseClicked(evt);
            }
        });
        MainPanel.add(balance);
        balance.setBounds(490, 340, 380, 40);

        username.setBackground(new java.awt.Color(116, 116, 116));
        username.setFont(new java.awt.Font("Prestige Elite Std", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText(" Username");
        username.setBorder(null);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        MainPanel.add(username);
        username.setBounds(490, 400, 380, 40);

        jSeparator3.setToolTipText("");
        MainPanel.add(jSeparator3);
        jSeparator3.setBounds(10, 670, 880, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MainPanel.add(jSeparator4);
        jSeparator4.setBounds(10, 90, 10, 580);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MainPanel.add(jSeparator5);
        jSeparator5.setBounds(440, 90, 10, 440);

        jSeparator6.setToolTipText("");
        MainPanel.add(jSeparator6);
        jSeparator6.setBounds(10, 530, 880, 10);

        jButton1.setBackground(new java.awt.Color(116, 116, 116));
        jButton1.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create Account");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        MainPanel.add(jButton1);
        jButton1.setBounds(650, 20, 240, 40);

        back.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componants/Back.png"))); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        MainPanel.add(back);
        back.setBounds(0, 0, 100, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/newaccount.jpg"))); // NOI18N
        MainPanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 680);

        getContentPane().add(MainPanel);
        MainPanel.setBounds(0, 20, 900, 740);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(UserLogin.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        AdminPanel AP=new AdminPanel();
        AP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        name.setText("");
    }//GEN-LAST:event_nameMouseClicked

    private void genderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderMouseClicked
        gender.setText("");
    }//GEN-LAST:event_genderMouseClicked

    private void ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageMouseClicked
        age.setText("");
    }//GEN-LAST:event_ageMouseClicked

    private void nidnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidnoMouseClicked
        nidno.setText("");
    }//GEN-LAST:event_nidnoMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        email.setText("");
    }//GEN-LAST:event_emailMouseClicked

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        address.setText("");
    }//GEN-LAST:event_addressMouseClicked

    private void contactnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactnoMouseClicked
        contactno.setText("");
    }//GEN-LAST:event_contactnoMouseClicked

    private void cardnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardnoMouseClicked
        cardno.setText("");
    }//GEN-LAST:event_cardnoMouseClicked

    private void cardpinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardpinMouseClicked
        cardpin.setText("");
    }//GEN-LAST:event_cardpinMouseClicked

    private void issuedateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedateMouseClicked
        issuedate.setText("");
    }//GEN-LAST:event_issuedateMouseClicked

    private void expiredateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiredateMouseClicked
        expiredate.setText("");
    }//GEN-LAST:event_expiredateMouseClicked

    private void acnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acnoMouseClicked
        acno.setText("");
    }//GEN-LAST:event_acnoMouseClicked

    private void actypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actypeMouseClicked
        actype.setText("");
    }//GEN-LAST:event_actypeMouseClicked

    private void branchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseClicked
       branch.setText("");
    }//GEN-LAST:event_branchMouseClicked

    private void interestrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interestrateMouseClicked
        interestrate.setText("");
    }//GEN-LAST:event_interestrateMouseClicked

    private void balanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceMouseClicked
       balance.setText("");
    }//GEN-LAST:event_balanceMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
       password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
        try{
          
          s="Insert into Users values('"+name.getText()+"','"+acno.getText()+"','"+branch.getText()+"','"+actype.getText()+"','"+address.getText()+"','"+contactno.getText()+"','"+email.getText()+"','"+Double.parseDouble(balance.getText())+"','"+nidno.getText()+"','"+Double.parseDouble(interestrate.getText())+"','"+Integer.parseInt(age.getText())+"','"+gender.getText()+"','"+username.getText()+"','"+password.getText()+"','"+cardno.getText()+"','"+cardpin.getText()+"','"+"No"+"','"+issuedate.getText()+"','"+expiredate.getText()+"','"+"No"+"')";
          ps=conn.prepareStatement(s);
          ps.execute();
          JOptionPane.showMessageDialog(this,"Account Created Sucessfully");
          
      }catch(Exception e){
          System.out.println("Not");
      }
        try{
            rs.close();
            ps.close();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        conn=Sqlite.ConnectDB(); 
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminTopPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField acno;
    private javax.swing.JTextField actype;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JLabel back;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField cardno;
    private javax.swing.JTextField cardpin;
    private javax.swing.JLabel close;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField email;
    private javax.swing.JTextField expiredate;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField interestrate;
    private javax.swing.JTextField issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nidno;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
